namespace WebService.Interfaces.Models
{
    public enum ContractCurrencyMode
    {
        EUR = 0,
        RUR = 1,
        USD = 2,
        JPY = 3,
        CHF = 4,
        GBP = 5,
        AUD = 6,
        AZN = 7,
        AMD = 8,
        BYR = 9,
        BGN = 10,
        BRL = 11,
        HUF = 12,
        DKK = 13,
        INR = 14,
        KZT = 15,
        CAD = 16,
        KGS = 17,
        CNY = 18,
        LVL = 19,
        LTL = 20,
        MDL = 21,
        NOK = 22,
        PLN = 23,
        RON = 24,
        XDR = 25,
        SGD = 26,
        TJS = 27,
        TRY = 28,
        TMT = 29,
        UZS = 30,
        UAH = 31,
        CZK = 32,
        SEK = 33,
        ZAR = 34,
        KRW = 35,
    }
}