<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>OpenBao</RootNamespace>
        <Description>Implementation of Settings Service extension, providing access to OpenBao secret store</Description>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="DocsVision.Settings.Client" Version="6.1.225-g8e7f192ab8" />
      <PackageReference Include="VaultSharp" Version="1.17.5.1" />
    </ItemGroup>
    

</Project>