//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadFilesBatchOperationDesignerExtension {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DownloadFilesBatchOperationDesignerExtension.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional files only.
        /// </summary>
        public static string DownloadDocumentFileMode_Additional {
            get {
                return ResourceManager.GetString("DownloadDocumentFileMode_Additional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string DownloadDocumentFileMode_All {
            get {
                return ResourceManager.GetString("DownloadDocumentFileMode_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main files only.
        /// </summary>
        public static string DownloadDocumentFileMode_Main {
            get {
                return ResourceManager.GetString("DownloadDocumentFileMode_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restriction folders (comma separated folder ids).
        /// </summary>
        public static string DownloadFilesBatchOperation_BatchOperationRestrictionFoldersPropertyName {
            get {
                return ResourceManager.GetString("DownloadFilesBatchOperation_BatchOperationRestrictionFoldersPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group operations / Download files.
        /// </summary>
        public static string DownloadFilesBatchOperation_ControlTypeName {
            get {
                return ResourceManager.GetString("DownloadFilesBatchOperation_ControlTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download mode.
        /// </summary>
        public static string DownloadFilesBatchOperation_DownloadDocumentFileModePropertyName {
            get {
                return ResourceManager.GetString("DownloadFilesBatchOperation_DownloadDocumentFileModePropertyName", resourceCulture);
            }
        }
    }
}
