//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcquaintancePanelDesignerExtension {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcquaintancePanelDesignerExtension.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample acquaintance side panel.
        /// </summary>
        public static string AcquaintancePanel {
            get {
                return ResourceManager.GetString("AcquaintancePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button text.
        /// </summary>
        public static string AcquaintancePanel_ButtonText {
            get {
                return ResourceManager.GetString("AcquaintancePanel_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On closed.
        /// </summary>
        public static string AcquaintancePanel_ClosedEvent {
            get {
                return ResourceManager.GetString("AcquaintancePanel_ClosedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On closing.
        /// </summary>
        public static string AcquaintancePanel_ClosingEvent {
            get {
                return ResourceManager.GetString("AcquaintancePanel_ClosingEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On opened.
        /// </summary>
        public static string AcquaintancePanel_OpenedEvent {
            get {
                return ResourceManager.GetString("AcquaintancePanel_OpenedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On opening.
        /// </summary>
        public static string AcquaintancePanel_OpeningEvent {
            get {
                return ResourceManager.GetString("AcquaintancePanel_OpeningEvent", resourceCulture);
            }
        }
    }
}
