
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     Created: 26.04.2017 15:47:51
// </autogenerated>
//------------------------------------------------------------------------------
using System;


namespace CustomLibrary.CustomLibrary.CardLib.CardDefs
{

	/// <summary>
	/// Константы CustomDirectory
	/// </summary>
	public static class CustomDirectory
	{
		/// <summary>
		/// Идентификатор карточки CustomDirectory
		/// </summary>
		public static readonly Guid ID = new Guid("43AE1738-9767-46C4-A04D-C31DFE3F5FCC");

		/// <summary>
		/// Алиас карточки CustomDirectory
		/// </summary>
		public const string Alias = "CustomDirectory";


		/// <summary>
		/// MainInfo section constants
		/// </summary>
		public static class MainInfo
		{
            /// <summary>
            /// Идентификатор секции MainInfo
            /// </summary>
            public static readonly Guid ID = new Guid("CA89F57A-0024-483B-9309-3A54AC16CED3");

			/// <summary>
			/// Алиас MainInfo
			/// </summary>
			public const string Alias = "MainInfo";


			/// <summary>
			/// Счётчик
			/// </summary>
			public const string Counter = "Counter";
		

		}


	}

}
