//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSPSignatureVisualizationServerExtension {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSPSignatureVisualizationServerExtension.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;text fill=&quot;#000000&quot; font-family=&quot;Arial&quot; style=&quot;white-space: pre&quot; font-size=&quot;10&quot; letter-spacing=&quot;0em&quot;&gt;
        ///	&lt;tspan x=&quot;9&quot; y=&quot;{0}&quot;&gt;LABEL:&lt;/tspan&gt;
        ///&lt;/text&gt;
        ///&lt;text fill=&quot;#000000&quot; style=&quot;white-space: pre&quot; font-family=&quot;Arial&quot; font-size=&quot;10&quot; letter-spacing=&quot;0.5em&quot;&gt;
        ///	&lt;tspan id=&quot;label&quot; x=&quot;80&quot; y=&quot;{0}&quot;&gt;{1}&lt;/tspan&gt;
        ///&lt;/text&gt;.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;text fill=&quot;#000000&quot; style=&quot;white-space: pre&quot; font-family=&quot;Arial&quot; font-size=&quot;10&quot; letter-spacing=&quot;0em&quot;&gt;
        ///	&lt;tspan x=&quot;9&quot; y=&quot;{0}&quot;&gt;Certificate:&lt;/tspan&gt;
        ///&lt;/text&gt;
        ///&lt;text fill=&quot;#000000&quot; style=&quot;white-space: pre&quot; font-family=&quot;Arial&quot; font-size=&quot;10&quot; letter-spacing=&quot;0em&quot;&gt;
        ///	&lt;tspan id=&quot;number&quot; x=&quot;85&quot; y=&quot;{0}&quot;&gt;{1}&lt;/tspan&gt;
        ///&lt;/text&gt;.
        /// </summary>
        internal static string SvgCertificateFragmentFormat {
            get {
                return ResourceManager.GetString("SvgCertificateFragmentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;/svg&gt;.
        /// </summary>
        internal static string SvgCloseTag {
            get {
                return ResourceManager.GetString("SvgCloseTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;text fill=&quot;#000000&quot; font-family=&quot;Arial&quot; style=&quot;white-space: pre&quot; font-size=&quot;10&quot; letter-spacing=&quot;0em&quot;&gt;
        ///	&lt;tspan x=&quot;9&quot; y=&quot;{0}&quot;&gt;LABEL:&lt;/tspan&gt;
        ///&lt;/text&gt;
        ///&lt;text fill=&quot;#000000&quot; style=&quot;white-space: pre&quot; font-family=&quot;Arial&quot; font-size=&quot;10&quot; letter-spacing=&quot;0.5em&quot;&gt;
        ///	&lt;tspan id=&quot;label&quot; x=&quot;85&quot; y=&quot;{0}&quot;&gt;{1}&lt;/tspan&gt;
        ///&lt;/text&gt;.
        /// </summary>
        internal static string SvgLabelFragmentFormat {
            get {
                return ResourceManager.GetString("SvgLabelFragmentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;image id=&quot;logo&quot; xlink:href=&quot;{0}&quot; x=&quot;200&quot; y=&quot;5&quot; height=&quot;37&quot; width=&quot;98&quot; /&gt;.
        /// </summary>
        internal static string SvgLogoFragmentFormat {
            get {
                return ResourceManager.GetString("SvgLogoFragmentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;text fill=&quot;#000000&quot; style=&quot;white-space: pre&quot; font-family=&quot;Arial&quot; font-size=&quot;10&quot; font-weight=&quot;bold&quot; letter-spacing=&quot;0em&quot;&gt;
        ///	&lt;tspan x=&quot;9&quot; y=&quot;{0}&quot;&gt;Owner:&lt;/tspan&gt;
        ///&lt;/text&gt;
        ///&lt;text fill=&quot;#000000&quot; style=&quot;white-space: pre&quot; font-family=&quot;Arial&quot; font-size=&quot;10&quot; font-weight=&quot;bold&quot; letter-spacing=&quot;0em&quot;&gt;
        ///	&lt;tspan id=&quot;owner1&quot; x=&quot;85&quot; y=&quot;{0}&quot;&gt;{1}&lt;/tspan&gt;
        ///&lt;/text&gt;.
        /// </summary>
        internal static string SvgOwnerFragmentFormat {
            get {
                return ResourceManager.GetString("SvgOwnerFragmentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;rect id=&quot;border&quot; x=&quot;0.5&quot; y=&quot;0.5&quot; width=&quot;{0}&quot; height=&quot;{1}&quot; rx=&quot;7.5&quot; stroke=&quot;#000000&quot;/&gt;.
        /// </summary>
        internal static string SvgRectFragmentFormat {
            get {
                return ResourceManager.GetString("SvgRectFragmentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;line x1=&quot;9&quot; y1=&quot;49.5&quot; x2=&quot;302&quot; y2=&quot;49.5&quot; stroke=&quot;#000000&quot; stroke-dasharray=&quot;1 2&quot;/&gt;
        ///&lt;text fill=&quot;#000000&quot; style=&quot;white-space: pre&quot; font-family=&quot;Arial&quot; font-size=&quot;13&quot; letter-spacing=&quot;0em&quot;&gt;
        ///	&lt;tspan x=&quot;9&quot; y=&quot;20.9434&quot;&gt;DOCUMENT IS SIGNED WITH&lt;/tspan&gt;
        ///	&lt;tspan x=&quot;9&quot; y=&quot;40.9434&quot;&gt;ELECTRONIC SIGNATURE&lt;/tspan&gt;
        ///&lt;/text&gt;.
        /// </summary>
        internal static string SvgTitleFragment {
            get {
                return ResourceManager.GetString("SvgTitleFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;text fill=&quot;#000000&quot; style=&quot;white-space: pre&quot; font-family=&quot;Arial&quot; font-size=&quot;10&quot; letter-spacing=&quot;0em&quot;&gt;
        ///	&lt;tspan x=&quot;9&quot; y=&quot;{0}&quot;&gt;Validness:&lt;/tspan&gt;
        ///&lt;/text&gt;
        ///&lt;text fill=&quot;#000000&quot; style=&quot;white-space: pre&quot; font-family=&quot;Arial&quot; font-size=&quot;10&quot; letter-spacing=&quot;0em&quot;&gt;
        ///	&lt;tspan id=&quot;date&quot; x=&quot;85&quot; y=&quot;{0}&quot;&gt;from {1} to {2}&lt;/tspan&gt;
        ///&lt;/text&gt;.
        /// </summary>
        internal static string SvgValidnessFragmentFormat {
            get {
                return ResourceManager.GetString("SvgValidnessFragmentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;svg viewBox=&quot;0 0 {0} {1}&quot; fill=&quot;none&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;
        ///	&lt;style&gt;
        ///		.hidden {{display: none;}}
        ///	&lt;/style&gt;.
        /// </summary>
        internal static string SvgViewboxOpenFragmentFormat {
            get {
                return ResourceManager.GetString("SvgViewboxOpenFragmentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;text fill=&quot;#000000&quot; style=&quot;white-space: pre&quot; font-family=&quot;Arial&quot; font-size=&quot;10&quot; letter-spacing=&quot;0.5em&quot;&gt;
        ///	&lt;tspan id=&quot;label&quot; x=&quot;85&quot; y=&quot;{0}&quot;&gt;{1}&lt;/tspan&gt;
        ///&lt;/text&gt;.
        /// </summary>
        internal static string SvgWrappedLabelFormat {
            get {
                return ResourceManager.GetString("SvgWrappedLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;text fill=&quot;#000000&quot; style=&quot;white-space: pre-line&quot; font-family=&quot;Arial&quot; font-size=&quot;10&quot; font-weight=&quot;bold&quot; letter-spacing=&quot;0em&quot;&gt;
        ///	&lt;tspan id=&quot;owner2&quot; x=&quot;85&quot; y=&quot;{0}&quot;&gt;{1}&lt;/tspan&gt;
        ///&lt;/text&gt;.
        /// </summary>
        internal static string SvgWrappedOwnerFormat {
            get {
                return ResourceManager.GetString("SvgWrappedOwnerFormat", resourceCulture);
            }
        }
    }
}