<Project Sdk="Microsoft.NET.Sdk">  
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<AssemblyName>DocsVision.SampleWorkerExtension.ServerExtension</AssemblyName>
	<EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Sign.snk" />
    <Content Include="Readme.md" />
    <EmbeddedResource Include="Resource.ru.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resource.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Autofac" Version="8.2.0" />
    <PackageReference Include="DocsVision.Platform.ObjectModel" Version="6.1.927" />
    <PackageReference Include="DocsVision.Platform.WebClient" Version="6.1.1444" />
    <PackageReference Include="DocsVision.WebClient" Version="6.1.1444" />
    <PackageReference Include="DocsVision.WebClient.Extensibility" Version="6.1.1444" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
  </ItemGroup>

  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyOriginatorKeyFile>Sign.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

</Project>