<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>DocsVision.ConversionSampleServerExtension</RootNamespace>
    <AssemblyName>DocsVision.ConversionSampleServerExtension</AssemblyName>
    <NoWarn>CS0618</NoWarn>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DocsVision.ConversionService" Version="6.1.20" />
    <PackageReference Include="DocsVision.Platform.Settings.ObjectModel" Version="6.1.110" />
    <PackageReference Include="DocsVision.WebClient.Extensibility" Version="6.1.1110" />
  </ItemGroup>

  <Target Name="_ModifyReferenceCopyLocalPaths" AfterTargets="ResolveAssemblyReferences">
    <ItemGroup>
      <ReferenceCopyLocalPaths Remove="@(ReferenceCopyLocalPaths)"
        Condition="'%(NuGetPackageId)' != 'DocsVision.ConversionService' and '%(NuGetPackageId)' != 'DocsVision.Platform.Settings.ObjectModel'" />
    </ItemGroup>
  </Target>

</Project>